# Generated by Django 4.0 on 2021-12-13 13:39

import EncryptedCharField
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalSource',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RDBMSInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rdbms_type', models.CharField(blank=True, choices=[('Oracle', 'Oracle'), ('DB2', 'DB2'), ('Postgres', 'Postgres')], max_length=100, null=True)),
                ('secret', EncryptedCharField.EncryptedCharField(blank=True, editable=True, max_length=256, null=True)),
                ('connection_string', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('canonical_fields', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_fields', models.CharField(blank=True, max_length=100, null=True)),
                ('where_clause', models.CharField(blank=True, max_length=100, null=True)),
                ('canonical_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', to='sync.canonicalsource')),
                ('rdbms_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', to='sync.rdbmsinstance')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUpdateJob',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('table_name', models.CharField(blank=True, max_length=100, null=True)),
                ('canonical_fields', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_fields', models.CharField(blank=True, max_length=100, null=True)),
                ('where_clause', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('canonical_source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sync.canonicalsource')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
                ('rdbms_instance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sync.rdbmsinstance')),
            ],
            options={
                'verbose_name': 'historical update job',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRDBMSInstance',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rdbms_type', models.CharField(blank=True, choices=[('Oracle', 'Oracle'), ('DB2', 'DB2'), ('Postgres', 'Postgres')], max_length=100, null=True)),
                ('secret', EncryptedCharField.EncryptedCharField(blank=True, editable=True, max_length=256, null=True)),
                ('connection_string', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
            ],
            options={
                'verbose_name': 'historical rdbms instance',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CanonicalUpdate',
            fields=[
                ('json', models.JSONField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=100, null=True)),
                ('canonical_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_updates', to='sync.canonicalsource')),
            ],
        ),
    ]
